-- Generated by database/migrations/build.ts. Do not edit this file directly.

begin;

-- BEGIN schema/004_playback.sql
create table public.watch_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.content(id) on delete cascade,
  episode_id uuid references public.episodes(id) on delete cascade,
  position_s double precision not null check (position_s between 0 and 86400),
  furthest_position_s double precision not null check (furthest_position_s between position_s and 86400),
  duration_s double precision not null check (duration_s > 0 and duration_s <= 86400 and position_s <= duration_s),
  updated_at timestamptz not null,
  unique nulls not distinct (user_id, content_id, episode_id)
);
create table public.watch_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.content(id) on delete cascade,
  episode_id uuid references public.episodes(id) on delete cascade,
  position_s double precision not null check (position_s between 0 and 86400),
  completed boolean not null default false,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null,
  unique nulls not distinct (user_id, content_id, episode_id)
);
create table public.bookmarks (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.content(id) on delete cascade,
  episode_id uuid references public.episodes(id) on delete cascade,
  position_s double precision not null check (position_s between 0 and 86400),
  title text not null check (length(btrim(title)) between 1 and 300),
  deleted boolean not null default false,
  updated_at timestamptz not null
);
create table public.playback_sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.content(id) on delete cascade,
  episode_id uuid references public.episodes(id) on delete cascade,
  position_s double precision not null check (position_s between 0 and 86400),
  started_at timestamptz not null default now(),
  updated_at timestamptz not null
);
create table public.playback_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  auto_next boolean not null default true,
  volume double precision not null default 1 check (volume between 0 and 1),
  muted boolean not null default false,
  playback_rate double precision not null default 1 check (playback_rate between 0.25 and 3),
  updated_at timestamptz not null default now()
);
-- END schema/004_playback.sql

-- BEGIN indexes/004_playback.sql
create index watch_history_user_updated_idx on public.watch_history(user_id, updated_at desc);
create index watch_progress_user_updated_idx on public.watch_progress(user_id, updated_at desc);
create index bookmarks_user_target_idx on public.bookmarks(user_id, content_id, episode_id, position_s);
create index playback_sessions_user_updated_idx on public.playback_sessions(user_id, updated_at desc);
create index watch_progress_content_idx on public.watch_progress(content_id);
create index watch_progress_episode_idx on public.watch_progress(episode_id);
create index watch_history_content_idx on public.watch_history(content_id);
create index watch_history_episode_idx on public.watch_history(episode_id);
create index bookmarks_content_idx on public.bookmarks(content_id);
create index bookmarks_episode_idx on public.bookmarks(episode_id);
create index playback_sessions_content_idx on public.playback_sessions(content_id);
create index playback_sessions_episode_idx on public.playback_sessions(episode_id);
-- END indexes/004_playback.sql

-- BEGIN functions/004_playback.sql
-- Protect monotonic progress even from a direct authenticated table update.
create function public.guard_playback_update() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  if new.updated_at < '1970-01-01'::timestamptz or new.updated_at > now() + interval '5 minutes' then
    raise exception 'Invalid playback timestamp';
  end if;
  if TG_OP = 'UPDATE' then
    if new.user_id <> old.user_id or new.content_id <> old.content_id
       or new.episode_id is distinct from old.episode_id or new.id <> old.id then
      raise exception 'Playback identity is immutable';
    end if;
    if TG_TABLE_NAME = 'watch_progress' then
      new.furthest_position_s := greatest(new.furthest_position_s, old.furthest_position_s, new.position_s);
      if new.updated_at <= old.updated_at then
        new.position_s := old.position_s;
        new.duration_s := old.duration_s;
        new.updated_at := old.updated_at;
      end if;
    elsif new.updated_at <= old.updated_at then return old;
    end if;
  end if;
  return new;
end $$;
create trigger watch_progress_guard before insert or update on public.watch_progress
for each row execute function public.guard_playback_update();
create trigger bookmarks_guard before insert or update on public.bookmarks
for each row execute function public.guard_playback_update();
create trigger playback_sessions_guard before insert or update on public.playback_sessions
for each row execute function public.guard_playback_update();

create function public.upsert_progress(
  p_content_id uuid, p_episode_id uuid, p_position_s double precision,
  p_furthest_position_s double precision, p_duration_s double precision,
  p_updated_at timestamptz, p_session_id uuid default null
) returns public.watch_progress
language plpgsql security invoker set search_path = '' as $$
declare saved public.watch_progress; caller uuid := auth.uid();
begin
  if caller is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  insert into public.watch_progress(user_id, content_id, episode_id, position_s, furthest_position_s, duration_s, updated_at)
  values(caller, p_content_id, p_episode_id, p_position_s, greatest(p_position_s, p_furthest_position_s), p_duration_s, p_updated_at)
  on conflict (user_id, content_id, episode_id) do update set
    position_s = excluded.position_s,
    furthest_position_s = greatest(watch_progress.furthest_position_s, excluded.furthest_position_s),
    duration_s = excluded.duration_s, updated_at = excluded.updated_at
  returning * into saved;

  insert into public.watch_history(user_id, content_id, episode_id, position_s, completed, updated_at)
  values(caller, p_content_id, p_episode_id, saved.position_s, saved.position_s >= saved.duration_s - least(10, saved.duration_s * 0.05), saved.updated_at)
  on conflict (user_id, content_id, episode_id) do update set
    position_s = case when excluded.updated_at > watch_history.updated_at then excluded.position_s else watch_history.position_s end,
    completed = watch_history.completed or excluded.completed,
    updated_at = greatest(watch_history.updated_at, excluded.updated_at);
  if p_session_id is not null then
    insert into public.playback_sessions(id, user_id, content_id, episode_id, position_s, updated_at)
    values(p_session_id, caller, p_content_id, p_episode_id, p_position_s, p_updated_at)
    on conflict (id) do update set position_s = excluded.position_s, updated_at = excluded.updated_at;
  end if;
  return saved;
end $$;
-- END functions/004_playback.sql

-- BEGIN policies/004_playback.sql
do $$ declare name text; begin
  foreach name in array array['watch_progress','watch_history','bookmarks','playback_sessions','playback_preferences'] loop
    execute format('alter table public.%I enable row level security', name);
    execute format('revoke all on public.%I from public, anon, authenticated', name);
    execute format('grant select, insert, update on public.%I to authenticated', name);
    execute format('grant select, insert, update, delete on public.%I to service_role', name);
    execute format('create policy own_rows on public.%I for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', name);
  end loop;
end $$;
-- Tombstones synchronize bookmark removals; progress cannot be deleted to reset its high-water mark.
revoke all on function public.guard_playback_update() from public, anon, authenticated;
revoke all on function public.upsert_progress(uuid, uuid, double precision, double precision, double precision, timestamptz, uuid) from public, anon;
grant execute on function public.upsert_progress(uuid, uuid, double precision, double precision, double precision, timestamptz, uuid) to authenticated;
-- END policies/004_playback.sql

commit;

