-- Generated by database/migrations/build.ts. Do not edit this file directly.

begin;

-- BEGIN schema/005_observability.sql
-- OBSERVABILITY. Client metadata is deliberately coarse; no raw user agent, URL, stack, or IP is stored.
create table public.playback_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  content_id uuid not null references public.content(id) on delete restrict,
  episode_id uuid references public.episodes(id) on delete set null,
  media_version_id uuid references public.media_versions(id) on delete set null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  event_type text not null check (event_type in ('session_started','playing','paused','session_snapshot','ended','buffering','seek','quality','error')),
  position_s double precision check (position_s is null or position_s between 0 and 86400),
  startup_ms double precision check (startup_ms is null or startup_ms between 0 and 86400000),
  watch_duration_ms double precision check (watch_duration_ms is null or watch_duration_ms between 0 and 86400000),
  total_buffer_ms double precision check (total_buffer_ms is null or total_buffer_ms between 0 and 86400000),
  completion_percentage double precision check (completion_percentage is null or completion_percentage between 0 and 100),
  failed_requests integer check (failed_requests is null or failed_requests between 0 and 10000),
  device text not null check (char_length(device) between 1 and 80),
  browser text not null check (char_length(browser) between 1 and 80),
  os text not null check (char_length(os) between 1 and 80),
  network text not null check (char_length(network) between 1 and 80),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object')
);

create table public.playback_errors (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  content_id uuid not null references public.content(id) on delete restrict,
  episode_id uuid references public.episodes(id) on delete set null,
  media_version_id uuid references public.media_versions(id) on delete set null,
  occurred_at timestamptz not null,
  code text not null check (char_length(code) between 1 and 120),
  category text not null check (category in ('network','manifest','media','drm','adapter','unknown')),
  fatal boolean not null,
  recoverable boolean not null,
  device text not null check (char_length(device) between 1 and 80),
  browser text not null check (char_length(browser) between 1 and 80),
  network text not null check (char_length(network) between 1 and 80)
);

create table public.buffering_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  content_id uuid not null references public.content(id) on delete restrict,
  episode_id uuid references public.episodes(id) on delete set null,
  media_version_id uuid references public.media_versions(id) on delete set null,
  occurred_at timestamptz not null,
  position_s double precision check (position_s is null or position_s between 0 and 86400),
  duration_ms double precision not null check (duration_ms between 0 and 86400000),
  device text not null check (char_length(device) between 1 and 80),
  browser text not null check (char_length(browser) between 1 and 80),
  network text not null check (char_length(network) between 1 and 80)
);

create table public.seek_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  content_id uuid not null references public.content(id) on delete restrict,
  episode_id uuid references public.episodes(id) on delete set null,
  media_version_id uuid references public.media_versions(id) on delete set null,
  occurred_at timestamptz not null,
  from_position_s double precision not null check (from_position_s between 0 and 86400),
  to_position_s double precision not null check (to_position_s between 0 and 86400),
  latency_ms double precision check (latency_ms is null or latency_ms between 0 and 86400000),
  device text not null check (char_length(device) between 1 and 80),
  browser text not null check (char_length(browser) between 1 and 80),
  network text not null check (char_length(network) between 1 and 80)
);

create table public.quality_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  content_id uuid not null references public.content(id) on delete restrict,
  episode_id uuid references public.episodes(id) on delete set null,
  media_version_id uuid references public.media_versions(id) on delete set null,
  occurred_at timestamptz not null,
  rendition_id text not null check (char_length(rendition_id) between 1 and 120),
  rendition_height integer check (rendition_height is null or rendition_height between 1 and 16384),
  rendition_bitrate integer check (rendition_bitrate is null or rendition_bitrate between 1 and 200000000),
  bandwidth_estimate double precision check (bandwidth_estimate is null or bandwidth_estimate between 0 and 10000000000),
  device text not null check (char_length(device) between 1 and 80),
  browser text not null check (char_length(browser) between 1 and 80),
  network text not null check (char_length(network) between 1 and 80)
);
-- END schema/005_observability.sql

-- BEGIN indexes/005_observability.sql
create index playback_events_session_occurred_idx on public.playback_events (session_id, occurred_at desc);
create index playback_events_occurred_idx on public.playback_events (occurred_at desc);
create index playback_errors_occurred_idx on public.playback_errors (occurred_at desc);
create index buffering_events_session_occurred_idx on public.buffering_events (session_id, occurred_at desc);
create index seek_events_occurred_idx on public.seek_events (occurred_at desc);
create index quality_events_dimensions_idx on public.quality_events (device, browser, network, rendition_id);
-- END indexes/005_observability.sql

-- BEGIN functions/005_observability.sql
create view public.analytics_video_startup_time
with (security_invoker = true, security_barrier = true) as
select count(*)::bigint as samples,
       percentile_cont(0.5) within group (order by startup_ms)::double precision as p50_ms,
       percentile_cont(0.95) within group (order by startup_ms)::double precision as p95_ms
from public.playback_events
where event_type = 'session_started' and startup_ms is not null;

create view public.analytics_seek_response_time
with (security_invoker = true, security_barrier = true) as
select count(*)::bigint as samples,
       percentile_cont(0.5) within group (order by latency_ms)::double precision as p50_ms,
       percentile_cont(0.95) within group (order by latency_ms)::double precision as p95_ms
from public.seek_events
where latency_ms is not null;

create view public.analytics_rebuffer_ratio
with (security_invoker = true, security_barrier = true) as
with latest as (
  select distinct on (session_id) session_id, total_buffer_ms, watch_duration_ms
  from public.playback_events
  where event_type = 'session_snapshot'
  order by session_id, occurred_at desc, id desc
)
select count(*)::bigint as samples,
       coalesce(sum(total_buffer_ms) / nullif(sum(watch_duration_ms), 0), 0)::double precision as ratio
from latest;

create view public.analytics_playback_error_rate
with (security_invoker = true, security_barrier = true) as
with sessions as (
  select distinct session_id from public.playback_events where event_type = 'session_snapshot'
), failures as (
  select distinct session_id from public.playback_errors
)
select count(sessions.session_id)::bigint as sessions,
       count(failures.session_id)::bigint as failed_sessions,
       coalesce(count(failures.session_id)::double precision / nullif(count(sessions.session_id), 0), 0)::double precision as error_rate
from sessions left join failures using (session_id);

create view public.analytics_average_selected_quality
with (security_invoker = true, security_barrier = true) as
select device, browser, network, rendition_id, rendition_height, rendition_bitrate,
       count(*)::bigint as selections,
       avg(bandwidth_estimate)::double precision as average_bandwidth_estimate
from public.quality_events
group by device, browser, network, rendition_id, rendition_height, rendition_bitrate;
-- END functions/005_observability.sql

-- BEGIN policies/005_observability.sql
-- The loop applies: revoke all on table public.playback_events from public, anon, authenticated
do $$ declare name text; begin
  foreach name in array array['playback_events','playback_errors','buffering_events','seek_events','quality_events'] loop
    execute format('alter table public.%I enable row level security', name);
    execute format('revoke all on table public.%I from public, anon, authenticated', name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', name);
  end loop;
end $$;

revoke all on table public.analytics_video_startup_time from public, anon, authenticated;
revoke all on table public.analytics_seek_response_time from public, anon, authenticated;
revoke all on table public.analytics_rebuffer_ratio from public, anon, authenticated;
revoke all on table public.analytics_playback_error_rate from public, anon, authenticated;
revoke all on table public.analytics_average_selected_quality from public, anon, authenticated;
grant select on table public.analytics_video_startup_time, public.analytics_seek_response_time,
  public.analytics_rebuffer_ratio, public.analytics_playback_error_rate,
  public.analytics_average_selected_quality to service_role;
-- END policies/005_observability.sql

commit;

