-- Generated by database/migrations/build.ts. Do not edit this file directly.

begin;

-- BEGIN schema/007_ai.sql
create table public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid references public.content(id) on delete cascade,
  episode_id uuid references public.episodes(id) on delete cascade,
  title text check (title is null or length(btrim(title)) between 1 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.ai_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null check (length(btrim(content)) between 1 and 100000),
  citations jsonb not null default '[]'::jsonb check (jsonb_typeof(citations) = 'array'),
  model text,
  created_at timestamptz not null default now()
);

create table public.ai_cache (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  cache_key text not null unique check (cache_key ~ '^[a-f0-9]{64}$'),
  task_type text not null check (task_type in ('cheap_chat','complex_reasoning','embedding','transcription','vision')),
  provider text not null check (btrim(provider) <> ''),
  model text not null check (btrim(model) <> ''),
  response jsonb not null,
  expires_at timestamptz not null,
  hit_count bigint not null default 0 check (hit_count >= 0),
  created_at timestamptz not null default now()
);

create table public.ai_usage (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique,
  user_id uuid references auth.users(id) on delete set null,
  conversation_id uuid references public.ai_conversations(id) on delete set null,
  task_type text not null check (task_type in ('cheap_chat','complex_reasoning','embedding','transcription','vision')),
  provider text not null check (btrim(provider) <> ''),
  model text not null check (btrim(model) <> ''),
  cost_tier text not null check (cost_tier in ('low','standard','premium')),
  attempts integer not null check (attempts between 1 and 20),
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  total_tokens integer generated always as (input_tokens + output_tokens) stored,
  cost_usd numeric(12,8) not null default 0 check (cost_usd >= 0),
  duration_ms integer not null check (duration_ms >= 0),
  success boolean not null,
  error_code text,
  created_at timestamptz not null default now()
);

create table public.ai_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  maximum_cost_tier text not null default 'standard' check (maximum_cost_tier in ('low','standard','premium')),
  preferred_language text,
  allow_history boolean not null default true,
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  updated_at timestamptz not null default now()
);
-- END schema/007_ai.sql

-- BEGIN indexes/007_ai.sql
create index ai_conversations_user_updated_idx on public.ai_conversations(user_id, updated_at desc);
create index ai_messages_conversation_created_idx on public.ai_messages(conversation_id, created_at);
create index ai_messages_user_idx on public.ai_messages(user_id);
create index ai_cache_user_expires_idx on public.ai_cache(user_id, expires_at);
create index ai_cache_expires_idx on public.ai_cache(expires_at);
create index ai_usage_user_created_idx on public.ai_usage(user_id, created_at desc);
create index ai_usage_task_created_idx on public.ai_usage(task_type, created_at desc);
create index ai_usage_conversation_idx on public.ai_usage(conversation_id);
-- END indexes/007_ai.sql

-- BEGIN functions/007_ai.sql
create or replace function public.guard_ai_message_owner()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.ai_conversations c
    where c.id = new.conversation_id and c.user_id = new.user_id
  ) then
    raise exception using errcode = '23503', message = 'Message owner must match conversation owner';
  end if;
  return new;
end;
$$;

create trigger ai_messages_owner_guard
before insert or update on public.ai_messages
for each row execute function public.guard_ai_message_owner();

revoke all on function public.guard_ai_message_owner() from public, anon, authenticated;
grant execute on function public.guard_ai_message_owner() to service_role;
-- END functions/007_ai.sql

-- BEGIN policies/007_ai.sql
do $$ declare name text; begin
  foreach name in array array['ai_conversations','ai_messages','ai_cache','ai_usage','ai_preferences'] loop
    execute format('alter table public.%I enable row level security', name);
    execute format('revoke all on table public.%I from public, anon, authenticated', name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', name);
  end loop;
end $$;

grant select, insert, update, delete on public.ai_conversations, public.ai_messages, public.ai_preferences to authenticated;
grant select on public.ai_usage to authenticated;

create policy ai_conversations_select_own on public.ai_conversations for select to authenticated using ((select auth.uid()) = user_id);
create policy ai_conversations_insert_own on public.ai_conversations for insert to authenticated with check ((select auth.uid()) = user_id);
create policy ai_conversations_update_own on public.ai_conversations for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy ai_conversations_delete_own on public.ai_conversations for delete to authenticated using ((select auth.uid()) = user_id);

create policy ai_messages_select_own on public.ai_messages for select to authenticated using ((select auth.uid()) = user_id);
create policy ai_messages_insert_own on public.ai_messages for insert to authenticated with check ((select auth.uid()) = user_id);
create policy ai_messages_update_own on public.ai_messages for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy ai_messages_delete_own on public.ai_messages for delete to authenticated using ((select auth.uid()) = user_id);

create policy ai_usage_select_own on public.ai_usage for select to authenticated using ((select auth.uid()) = user_id);

create policy ai_preferences_select_own on public.ai_preferences for select to authenticated using ((select auth.uid()) = user_id);
create policy ai_preferences_insert_own on public.ai_preferences for insert to authenticated with check ((select auth.uid()) = user_id);
create policy ai_preferences_update_own on public.ai_preferences for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy ai_preferences_delete_own on public.ai_preferences for delete to authenticated using ((select auth.uid()) = user_id);
-- END policies/007_ai.sql

commit;

