import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

export const MIGRATION_PARTS = [
  "schema/001_auth_catalog_media.sql",
  "indexes/001_auth_catalog_media.sql",
  "policies/001_auth_catalog_media.sql",
  "functions/001_auth_catalog_media.sql",
] as const;

const BuildOptionsSchema = z
  .object({
    databaseRoot: z.string().trim().min(1),
    outputPath: z.string().trim().min(1),
  })
  .strict();

export type BuildMigrationOptions = z.infer<typeof BuildOptionsSchema>;

async function renderLayeredMigration(databaseRoot: string, name: string): Promise<string> {
  const parts = ["schema", "indexes", "functions", "policies"].map(
    (layer) => `${layer}/${name}.sql`,
  );
  const sections = await Promise.all(
    parts.map(
      async (part) =>
        `-- BEGIN ${part}\n${(await readFile(join(databaseRoot, part), "utf8")).trim()}\n-- END ${part}`,
    ),
  );
  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export const renderIntelligenceMigration = (databaseRoot: string) =>
  renderLayeredMigration(databaseRoot, "006_intelligence");

export const renderAiMigration = (databaseRoot: string) =>
  renderLayeredMigration(databaseRoot, "007_ai");

export const renderAiRetrievalMigration = (databaseRoot: string) =>
  renderLayeredMigration(databaseRoot, "008_ai_retrieval");

export async function renderPlaybackMigration(databaseRoot: string): Promise<string> {
  const parts = ["schema", "indexes", "functions", "policies"].map(
    (layer) => `${layer}/004_playback.sql`,
  );
  const sections = await Promise.all(
    parts.map(
      async (part) =>
        `-- BEGIN ${part}\n${(await readFile(join(databaseRoot, part), "utf8")).trim()}\n-- END ${part}`,
    ),
  );
  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export async function renderObservabilityMigration(databaseRoot: string): Promise<string> {
  const parts = ["schema", "indexes", "functions", "policies"].map(
    (layer) => `${layer}/005_observability.sql`,
  );
  const sections = await Promise.all(
    parts.map(
      async (part) =>
        `-- BEGIN ${part}\n${(await readFile(join(databaseRoot, part), "utf8")).trim()}\n-- END ${part}`,
    ),
  );
  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export async function renderSubtitleMigration(databaseRoot: string): Promise<string> {
  const parts = [
    "schema/003_subtitle_variants.sql",
    "functions/003_subtitle_variants.sql",
    "policies/003_subtitle_variants.sql",
  ];
  const sections = await Promise.all(
    parts.map(
      async (part) =>
        `-- BEGIN ${part}\n${(await readFile(join(databaseRoot, part), "utf8")).trim()}\n-- END ${part}`,
    ),
  );
  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export async function renderPublicationMigration(databaseRoot: string): Promise<string> {
  const parts = [
    "schema/002_publication.sql",
    "indexes/002_publication.sql",
    "functions/002_publication.sql",
    "policies/002_publication.sql",
  ];
  const sections = await Promise.all(
    parts.map(
      async (part) =>
        `-- BEGIN ${part}\n${(await readFile(join(databaseRoot, part), "utf8")).trim()}\n-- END ${part}`,
    ),
  );
  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export async function renderAuthCatalogMediaMigration(databaseRoot: string): Promise<string> {
  const root = resolve(z.string().trim().min(1).parse(databaseRoot));
  const sections: string[] = [];

  for (const relativePath of MIGRATION_PARTS) {
    const path = join(root, relativePath);
    const sql = z
      .string()
      .trim()
      .min(1)
      .parse(await readFile(path, "utf8"));
    if (/\b(?:TODO|FIXME)\b/.test(sql)) {
      throw new Error(`Migration source contains an unfinished marker: ${relativePath}`);
    }
    sections.push(`-- BEGIN ${relativePath}\n${sql}\n-- END ${relativePath}`);
  }

  return [
    "-- Generated by database/migrations/build.ts. Do not edit this file directly.",
    "begin;",
    ...sections,
    "commit;",
    "",
  ].join("\n\n");
}

export async function buildAuthCatalogMediaMigration(
  options: BuildMigrationOptions,
): Promise<string> {
  const value = BuildOptionsSchema.parse(options);
  const outputPath = resolve(value.outputPath);
  const sql = await renderAuthCatalogMediaMigration(value.databaseRoot);
  const temporaryPath = `${outputPath}.${process.pid}.${Date.now()}.tmp`;
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(temporaryPath, sql, { encoding: "utf8", flag: "wx" });
  await rename(temporaryPath, outputPath);
  return outputPath;
}

async function main(): Promise<void> {
  const databaseRoot = fileURLToPath(new URL("..", import.meta.url));
  const outputPath = process.argv[2]
    ? resolve(process.argv[2])
    : join(databaseRoot, "migrations", "001_auth_catalog_media.sql");
  const parsed = z
    .object({ outputPath: z.string().trim().min(1) })
    .strict()
    .parse({ outputPath });
  process.stdout.write(
    `${await buildAuthCatalogMediaMigration({ databaseRoot, outputPath: parsed.outputPath })}\n`,
  );
  if (!process.argv[2]) {
    const publicationPath = join(databaseRoot, "migrations", "002_publication.sql");
    await writeFile(publicationPath, await renderPublicationMigration(databaseRoot), "utf8");
    process.stdout.write(`${publicationPath}\n`);
    const subtitlePath = join(databaseRoot, "migrations", "003_subtitle_variants.sql");
    await writeFile(subtitlePath, await renderSubtitleMigration(databaseRoot), "utf8");
    process.stdout.write(`${subtitlePath}\n`);
    const playbackPath = join(databaseRoot, "migrations", "004_playback.sql");
    await writeFile(playbackPath, await renderPlaybackMigration(databaseRoot), "utf8");
    process.stdout.write(`${playbackPath}\n`);
    const observabilityPath = join(databaseRoot, "migrations", "005_observability.sql");
    await writeFile(observabilityPath, await renderObservabilityMigration(databaseRoot), "utf8");
    process.stdout.write(`${observabilityPath}\n`);
    const intelligencePath = join(databaseRoot, "migrations", "006_intelligence.sql");
    await writeFile(intelligencePath, await renderIntelligenceMigration(databaseRoot), "utf8");
    process.stdout.write(`${intelligencePath}\n`);
    const aiPath = join(databaseRoot, "migrations", "007_ai.sql");
    await writeFile(aiPath, await renderAiMigration(databaseRoot), "utf8");
    process.stdout.write(`${aiPath}\n`);
    const retrievalPath = join(databaseRoot, "migrations", "008_ai_retrieval.sql");
    await writeFile(retrievalPath, await renderAiRetrievalMigration(databaseRoot), "utf8");
    process.stdout.write(`${retrievalPath}\n`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  void main().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
